export const BASE_URL = import.meta.env.BASE_URL

export const profile = {
  name: '崔紫燕',
  title: '短视频内容运营',
  hero: {
    badge: 'CREATIVE PORTFOLIO 作品集',
    title: '欢迎来到我的个人网站',
    subtitle: '崔紫燕｜短视频内容运营',
    tag: '4 年短视频内容经验｜国内 & 海外项目经历',
  },
  polaroids: {
    pro: { img: `${BASE_URL}media/polaroids/pro.jpg`, caption: '2025 · 内容创作' },
    cute: { img: `${BASE_URL}media/polaroids/cute.jpg`, caption: 'Keep creating ✎' },
  },
  about: {
    heading: '个人简介',
    tags: [
      '甲方实战经验',
      '乙方 4A 广告公司经验',
      '国内新媒体运营经验',
      '海外新媒体运营经验',
    ],
  },
  phone: '15083528515',
  email: 'zc1049797791@163.com',
  location: '广东 · 东莞',
  relocation: '可接受广东省内工作调动',
  education: '南昌大学 · 广告学本科（国家“211 工程”高校）',
  avatar: `${BASE_URL}media/avatar.jpg`,
  heroVideo: `${BASE_URL}media/videos/hero.mp4`,
  heroPoster: `${BASE_URL}media/posters/hero.jpg`,
  resumeUrl: `${BASE_URL}CuiZiyan-Resume.pdf`,
}

export const timeline = [
  {
    period: '2024.04 – 2026.07',
    company: 'KK集团（X11 潮玩）',
    role: '新媒体运营',
    brief:
      '从 0→1 搭建全国 170+ 家门店新媒体矩阵，覆盖门店账号创建、同城选题策划、内容模板输出到辅导门店拍摄与发布的全链路，形成标准化可复制的运营体系；负责「X11 潮玩精选」官方账号全周期运营，结合行业热点、新品与 IP 联名策划内容；从零搭建 KOC 素人种草矩阵，沉淀品牌私域创作者社群。',
    results: [
      { v: '4.7 万', k: '门店原创笔记' },
      { v: '969', k: '平台爆文' },
      { v: '750 万', k: '门店矩阵曝光' },
      { v: '5 万', k: '官方账号粉丝' },
      { v: '90 万+', k: '累计互动' },
    ],
  },
  {
    period: '2022.07 – 2024.03',
    company: '广州超帆信息科技有限公司（Guru Online）',
    role: '海外短视频创意',
    brief:
      '独立产出 300+ 条海外中英文短视频脚本，深耕 3C 数码、汽车赛道，深度参与 TikTok for Business、CapCut 官方合作项目，服务 realme、vivo、奇瑞汽车、MG 汽车等品牌；统筹短视频全流程落地，对接拍摄、剪辑团队与品牌客户，把控脚本、镜头与后期制作标准；后期牵头小型创意团队。',
    results: [
      { v: '1800 万', k: '作品最高播放量' },
      { v: '2 万', k: '单账号月最高涨粉' },
      { v: '300+', k: '独立撰写双语脚本' },
    ],
  },
  {
    period: '2022.01 – 2022.04',
    company: '金山文档',
    role: '新媒体运营实习生',
    brief: '负责抖音、B 站短视频脚本撰写与选题策划，独立运营小红书账号，打通内容全链路产出。',
    results: [{ v: '10%', k: '小红书账号涨粉' }],
  },
]

export const navItems = [
  { id: 'about', label: '关于我' },
  { id: 'projects', label: '精选项目' },
  { id: 'strengths', label: '个人优势' },
  { id: 'contact', label: '联系我' },
]

export const stats = [
  {
    value: '1800 万',
    label: '单条最高播放',
    sub: '单月账号最高涨粉 2 万',
    tone: 'rose',
  },
  {
    value: '5 万+',
    label: 'X11 官方账号粉丝',
    sub: '2k → 5w+ · 累计互动 90w+',
    tone: 'bean',
  },
  {
    value: '4.7 万',
    label: '门店矩阵笔记',
    sub: '969 篇平台爆文',
    tone: 'rose',
  },
  {
    value: '159 万',
    label: 'KOC 矩阵曝光',
    sub: '48 场招募 · 500+ 创作者社群',
    tone: 'bean',
  },
]

export const projects = [
  {
    id: 'x11-matrix',
    no: '01',
    title: 'X11 潮玩｜全国门店新媒体矩阵 0→1 搭建',
    tags: ['矩阵搭建', '门店赋能', '小红书'],
    desc: '搭建 170+ 门店新媒体矩阵，输出标准化内容体系；产出 4.7 万篇笔记、969 篇爆文，撬动同城到店流量。',
    results: [
      { v: '170+', k: '门店矩阵' },
      { v: '4.7 万', k: '原创笔记' },
      { v: '969', k: '平台爆文' },
    ],
    video: `${BASE_URL}media/videos/x11-matrix.mp4`,
    poster: `${BASE_URL}media/posters/x11-matrix.jpg`,
    videoLabel: '门店账号内容案例成片',
    videos: [
      {
        id: 'v1',
        title: '案例视频 01 · 门店账号内容成片',
        desc: '多家门店账号内容精选，展示标准化内容模板与同城爆款的产出效果。',
        video: `${BASE_URL}media/videos/x11-matrix.mp4`,
        poster: `${BASE_URL}media/posters/x11-matrix.jpg`,
        link: '',
        linkLabel: '打开原视频',
      },
      {
        id: 'v2',
        title: '案例视频 02 · 门店运营链路示范',
        desc: '从选题、拍摄到发布的门店内容全链路示范，体现可复制的运营体系。',
        video: `${BASE_URL}media/videos/x11-matrix-2.mp4`,
        poster: `${BASE_URL}media/posters/x11-matrix.jpg`,
        link: '',
        linkLabel: '打开原视频',
      },
      {
        id: 'v3',
        title: '案例视频 03 · 到店流量承接',
        desc: '爆文内容如何反哺线下的到店流量承接案例。',
        video: `${BASE_URL}media/videos/x11-matrix-3.mp4`,
        poster: `${BASE_URL}media/posters/x11-matrix.jpg`,
        link: '',
        linkLabel: '打开原视频',
      },
    ],
    tone: 'rose',
  },
  {
    id: 'x11-official',
    no: '02',
    title: 'X11 潮玩｜官方账号全周期运营',
    tags: ['官方账号', '抖音', '小红书', '内容运营'],
    desc: '负责「X11 潮玩精选」官方账号，从 0 做到 5 万+ 粉丝；热点、新品与 IP 联名内容策划，全流程独立运营。',
    results: [
      { v: '5 万+', k: '粉丝增长' },
      { v: '90 万+', k: '累计互动' },
      { v: '130 万', k: '单条最高播放' },
    ],
    video: `${BASE_URL}media/videos/x11-official.mp4`,
    poster: `${BASE_URL}media/posters/x11-official.jpg`,
    videoLabel: '官方账号爆款案例视频',
    videos: [
      {
        id: 'v1',
        title: '案例视频 01 · 官方账号爆款',
        desc: '「X11 潮玩精选」高互动爆款内容精选，覆盖抖音与小红书。',
        video: `${BASE_URL}media/videos/x11-official.mp4`,
        poster: `${BASE_URL}media/posters/x11-official.jpg`,
        link: '',
        linkLabel: '打开原视频',
      },
      {
        id: 'v2',
        title: '案例视频 02 · 新品与 IP 联名内容',
        desc: '结合品牌新品与 IP 联名策划的热点内容示例。',
        video: `${BASE_URL}media/videos/x11-official-2.mp4`,
        poster: `${BASE_URL}media/posters/x11-official.jpg`,
        link: '',
        linkLabel: '打开原视频',
      },
      {
        id: 'v3',
        title: '案例视频 03 · 账号增长拆解',
        desc: '从 2k 到 5w+ 粉丝的账号全周期运营节奏拆解。',
        video: `${BASE_URL}media/videos/x11-official-3.mp4`,
        poster: `${BASE_URL}media/posters/x11-official.jpg`,
        link: '',
        linkLabel: '打开原视频',
      },
    ],
    tone: 'bean',
  },
  {
    id: 'koc-matrix',
    no: '03',
    title: 'KOC 素人种草矩阵搭建',
    tags: ['素人矩阵', '种草营销', '私域'],
    desc: '48 场 KOC 招募，沉淀 500+ 创作者社群，小红书总曝光 159 万，产出 182 篇种草爆文。',
    results: [
      { v: '48', k: '场招募' },
      { v: '500+', k: '创作者社群' },
      { v: '182', k: '种草爆文' },
    ],
    video: `${BASE_URL}media/videos/koc-matrix.mp4`,
    poster: `${BASE_URL}media/posters/koc-matrix.jpg`,
    videoLabel: 'KOC 产出代表案例视频',
    videos: [
      {
        id: 'v1',
        title: '案例视频 01 · 插画小人最后抽一发❗️超全手感和重量',
        desc: 'KOC 素人种草图文笔记 · 互动 1,000 · 藏 200 · 评 80 · 转 300',
        video: '',
        poster: `${BASE_URL}media/covers/koc-c1-illustration-girl.jpg`,
        link: 'https://xhslink.cn/o/7OFmJCNELQM',
        linkLabel: '打开小红书原笔记',
        play: '—',
        like: '1,000',
        idea: '以「最后抽一发」的真实到店购买情绪做钩子，分享盲盒手感与重量细节，建立 KOC 真实种草感。',
        xiaohongshu: 'https://xhslink.cn/o/7OFmJCNELQM',
        douyin: '',
        note: '本案例为图文笔记，无视频源。',
        script: null,
      },
      {
        id: 'v2',
        title: '案例视频 02 · 背影一般？但正面真的很离谱啊 · X11 黄油小熊开箱',
        desc: 'KOC 素人种草视频 · 互动 1,700 · 藏 250 · 评 90 · 转 350',
        video: `${BASE_URL}media/videos/x11-koc-c3-butterbear.mp4`,
        poster: `${BASE_URL}media/covers/koc-c3-butterbear.jpg`,
        link: 'https://xhslink.cn/o/6AZYHk2e96E',
        linkLabel: '打开小红书原笔记',
        play: '—',
        like: '1,700',
        idea: '以「背影一般？但正面真的很离谱」的反差悬念做钩子，分享黄油小熊开箱手感与重量，撬动点击。',
        xiaohongshu: 'https://xhslink.cn/o/6AZYHk2e96E',
        douyin: '',
        script: null,
      },
      {
        id: 'v3',
        title: '案例视频 03 · 插画小人毛绒盲盒第二弹 · 召集 40 个爱玩的宝',
        desc: '官方发布公告 · 召集 KOC 参与种草的招募模板 · 报名 275 人 · 沉淀笔记 40 篇 · 浏览 8,000+',
        video: '',
        poster: `${BASE_URL}media/covers/koc-c2-recruit-campaign.jpg`,
        link: 'https://www.xiaohongshu.com/discovery/item/68a2ec09000000001d014546?source=webshare&xhsshare=pc_web&xsec_token=ABg-JDlpW-gsQBR0SGNnBjzV3jzv73TnCsXcY4lAb7mDo=&xsec_source=pc_share',
        linkLabel: '打开小红书原招募笔记',
        play: '8,000+',
        like: '275',
        idea: '「先由官方号在公域引导 → 进入私域系统筛选 → 产品寄出让用户自由创作」：本笔记是 X11 潮玩精选官方号发布的「插画小人毛绒盲盒第二弹 · 召集 40 个爱玩的宝」活动公告模板，面向 KOC 发出种草邀请；以「速来 40 位宝子」做钩子，官方号先在小红书公域放预告，引导用户进入「X11 种草官」小程序报名（活动共报名 275 人）；私域系统按报名顺序 + 创作者画像筛选 40 位体验官，把毛绒盲盒寄出后让用户在小红书自由创作，最终沉淀真实种草笔记 40 篇。',
        xiaohongshu: 'https://www.xiaohongshu.com/discovery/item/68a2ec09000000001d014546?source=webshare&xhsshare=pc_web&xsec_token=ABg-JDlpW-gsQBR0SGNnBjzV3jzv73TnCsXcY4lAb7mDo=&xsec_source=pc_share',
        douyin: '',
        note: '本案例为招募活动图文，无视频源。',
        script: null,
      },
    ],
    tone: 'rose',
  },
  {
    id: 'guru-overseas',
    no: '04',
    title: 'Guru Online｜海外短视频创意项目',
    tags: ['TikTok', '海外短视频', '品牌服务'],
    desc: '产出 300+ 海外脚本，服务 realme、vivo、奇瑞等品牌；打造千万播放爆款，统筹小型创意团队。',
    results: [
      { v: '300+', k: '海外脚本' },
      { v: '1800万', k: '爆款播放' },
      { v: '2 万', k: '单月最高涨粉' },
    ],
    video: `${BASE_URL}media/videos/guru-overseas.mp4`,
    poster: `${BASE_URL}media/posters/guru-overseas.jpg`,
    videoLabel: '海外品牌短视频案例成片',
    videos: [
      {
        id: 'v1',
        title: 'MG 秋天 TVC',
        playerTitle: 'MG 秋天 TVC',
        desc: 'MG4 海外秋日 TVC 真实成片，主角逃离沉重繁忙的城市，独自驾驶 MG 4 汽车享受秋日的静谧与美好。',
        play: '—',
        like: '—',
        video: `${BASE_URL}media/videos/x11-guru-c1-mg4-tvc-autumn.mp4`,
        poster: `${BASE_URL}media/covers/x11-guru-c1-mg4-tvc-autumn.jpg`,
        idea: '以「逃离城市 · 静谧秋日」为情绪主线：主角从压抑、节奏密集的城市日常抽离，独自驾驶 MG 4 驶入秋日郊野，通过车窗外流动的金黄落叶、逆光剪影、空旷公路等镜头语言，把「沉重繁忙 vs 静谧美好」的城市/自然对立拉满；本人主导创意方向，独立完成中英文双语 TC 脚本撰写，自主对接海外摄影摄制资源，与海外摄制团队远程沟通，统筹拍摄全流程，敲定镜头与场景细节，最终完成品牌 TVC 交付。',
        douyin: '',
        xiaohongshu: '',
        youtube: 'https://youtu.be/7cuDlETVumI?si=lAMY4RASQBdoPnaR',
        script: null,
      },
      {
        id: 'v2',
        title: 'Get Ready with MG',
        playerTitle: 'Get Ready with MG',
        desc: 'MG4 海外 TVC 真实成片 · 通过各种巧妙转场展示不同的 MG4 车身颜色。',
        play: '—',
        like: '—',
        video: `${BASE_URL}media/videos/x11-guru-c2-mg4-different-colors.mp4`,
        poster: `${BASE_URL}media/covers/x11-guru-c2-mg4-different-colors.jpg`,
        idea: '以「**红绿灯 + 马路场景**」为画面节奏指挥棒：红绿灯切换、汽车转弯、街角回眸等马路节拍同步带动「**模特服装妆造 + MG4 车身色**」色彩切换（红灯=红衣+红 MG4 / 绿灯=浅色风衣+银 MG4 / 黄灯=黄橙 MG4），把「同款不同色」做成可被「红绿灯 / 转弯 / 街角」驱动的叙事节奏。本人主导创意 + 中英文双语 TC 脚本 + 海外摄制对接 + 色彩节点把控，完成品牌 TVC 交付。',
        douyin: '',
        xiaohongshu: '',
        youtube: 'https://youtu.be/wEJjMRa_pmY?si=DeKdrTWeyvffVHD7',
        script: null,
      },
      {
        id: 'v3',
        title: '案例视频 03 · 奇瑞 TIGGO 2 PRO · DAY AND NIGHT 日夜转场',
        playerTitle: '案例视频 03 · 奇瑞 TIGGO 2 PRO · DAY AND NIGHT 日夜转场',
        desc: '奇瑞墨西哥出海成片 · 日夜转场展示 TIGGO 2 PRO 外饰细节与灯光内饰细节。',
        play: '—',
        like: '—',
        video: `${BASE_URL}media/videos/x11-guru-c3-chery-tigo-day-night.mp4`,
        poster: `${BASE_URL}media/covers/x11-guru-c3-chery-tigo-day-night.jpg`,
        tiktok: 'https://www.tiktok.com/@chireymexicoofficial/video/7323051694026181921',
        idea: '以「DAY AND NIGHT」日夜转场为创意主线：通过「白昼自然光 → 黄昏暖光 → 深夜氛围灯」三段式节奏，依次展示 TIGGO 2 PRO 的外饰细节（尾部 TIGGO 2 PRO 标识、前脸中网格栅、点阵日行灯）与内饰细节（几何纹理饰板、蓝色氛围灯带、红色尾灯组合），用光线变化把产品细节的材质感拉到最大。本人主导创意方向与 TC 脚本撰写，统筹广州本地拍摄执行与后期剪辑，把控镜头节奏与色彩一致性，最终完成面向墨西哥市场的海外出海成片。',
        douyin: '',
        xiaohongshu: '',
        script: null,
      },
      {
        id: 'v4',
        title: '案例视频 04 · 南方新闻网海外专题',
        playerTitle: '案例视频 04 · 南方新闻网海外专题',
        desc: '面向海外用户制作传播广东地域文化的短视频专题。',
        play: '680W',
        like: '24W',
        video: `${BASE_URL}media/videos/x11-guru-c4-nanfang-canton-tower.mp4`,
        poster: `${BASE_URL}media/covers/x11-guru-c4-nanfang-canton-tower.jpg`,
        idea: '受南方新闻网品牌委托，**于广州本地拍摄**，以广州塔为单一视觉锚点，串联「白天草地 → 暮色旗袍 → 夜塔红绿亮灯」三段时间流逝，通过「现代服装 ↔ 旗袍」真人变装转场 + 「日景 ↔ 夜景 + 火花特效」光线节奏，把广州塔作为国际地标的跨时段魅力压缩到一支短片里。本人主导选题策划与脚本创意撰写，**统筹现场执行与跟拍**（导演、演员、摄影、灯光、后期剪辑全流程把控），把控品牌对外传播调性。',
        douyin: '',
        xiaohongshu: '',
        script: null,
      },
      {
        id: 'v5',
        title: '案例视频 05 · realme 海外成片',
        playerTitle: '案例视频 05 · realme 海外成片',
        desc: 'realme 海外短视频创意与成片交付。',
        play: '—',
        like: '—',
        video: `${BASE_URL}media/videos/x11-guru-c5-realme-rockstar.mp4`,
        poster: `${BASE_URL}media/covers/x11-guru-c5-realme-rockstar.jpg`,
        idea: '核心在于传达「**手机 + 耳机的沉浸式产品性能**」——**手机与耳机都能带来极具沉浸式的体验，让人一秒变身摇滚巨星**。主角打开手机 + 戴上耳机播放音乐的那一刻，画面从灰白「物理现实」瞬间切换到「沉浸式音效 + 视觉」共同构建的内心摇滚世界，承接 realme 海外「敢玩敢造」品牌调性，把「**手机 + 耳机 = 沉浸式产品性能 + 一秒变身摇滚巨星**」直接做成画面语言。本人主导创意 + 脚本 + 海外摄制统筹 + 后期剪辑把控，完成品牌海外成片交付。',
        douyin: '',
        xiaohongshu: '',
        script: null,
      },
    ],
    tone: 'bean',
  },
]

export const officialDetail = {
  id: 'x11-official',
  tagline: '过去 2 年，我一人负责一个官方账号，慢慢把它做到了 5W 粉丝增长。',
  meta: '项目周期：2024.04–2026.07｜平台：抖音、小红书｜角色：独立全流程运营',
  note: '行业参考值为同类目账号后台均值',
  dashboards: [
    {
      label: '账号增长成果',
      value: '5W',
      desc: '账号累计增长 5W，高于同行平均增长水平（2W）',
      mine: 5,
      peer: 2,
      max: 5,
      unit: 'W',
      icon: 'trend',
    },
    {
      label: '累计互动量',
      value: '90W',
      desc: '累计互动量达 90W，显著高于同行平均水平（50W）',
      mine: 90,
      peer: 50,
      max: 90,
      unit: 'W',
      icon: 'chat',
    },
    {
      label: '自然流峰值曝光',
      value: '100W+',
      donut: [
        { name: '自然流', pct: 80 },
        { name: '投流', pct: 20 },
      ],
      desc: '账号流量结构以自然流为主，占比约 80%，投流占比约 20%',
      icon: 'eye',
    },
    {
      label: '单人月均产出',
      value: '30篇',
      desc: '单人月均产出 30 篇，明显高于同行平均水平（12 篇）',
      mine: 30,
      peer: 12,
      max: 30,
      unit: '篇',
      icon: 'doc',
      note: '月产出 30 篇：包含短视频+图文内容',
    },
  ],
  tags: ['从冷启动到稳定增长', '爆款经验可复制到矩阵体系', '单人独立完成全流程运营'],
  points: [
    {
      keys: ['0-1 搭建', '冷启动到稳定增长'],
      text: '独立完成官方账号 0-1 搭建，实现从冷启动到稳定增长的完整运营闭环',
    },
    {
      keys: ['可复用内容方法论', '爆款内容'],
      text: '将账号运营经验沉淀为可复用内容方法论，并应用于门店矩阵，产出多条爆款内容',
    },
    {
      keys: ['内容策划、执行统筹与数据复盘'],
      text: '在项目推进过程中，持续提升内容策划、执行统筹与数据复盘能力',
    },
  ],
  cases: [
    {
      id: 'c1',
      title: '案例视频 01 · 哑巴设计师：那咋了？？？',
      playerTitle: '案例视频 01 · 哑巴设计师：那咋了？？？',
      desc: '开创账号独有的「一镜到底合集展示 + 悬念感标题封面」创作风格，成为账号最易产出爆款的内容形式。',
      play: '100W+',
      like: '3.5W',
      video: `${BASE_URL}media/videos/x11-official-c1-siamrip.mp4`,
      poster: `${BASE_URL}media/covers/c1.jpg`,
      idea: '在小红书平台观察到该产品已有万赞视频，验证了内容潜力。进一步拆解站内爆款后发现，用户对吧唧工艺的关注度很高，但相关内容多为单点呈现，缺少对整套产品的集中展示。由此切入，以极具悬念感的标题与封面引导点击，最终产出这条百万播放的爆款。',
      douyin: 'https://v.douyin.com/C-8jZMV0a2w/',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/6720a426000000001901a6d6?source=webshare&xhsshare=pc_web&xsec_token=ABpDmOL5h80pSWlgX_CrvQwGcEQNWpmU_H4Jyu-DlKAmA=&xsec_source=pc_share',
      script: null,
    },
    {
      id: 'c2',
      title: '案例视频 02 · 插画小人毛绒盲盒',
      playerTitle: '案例视频 02 · 插画小人毛绒盲盒',
      desc: '在原有风格上发掘「玩法介绍」这一强利他内容概念，为账号内容运营打开更多新方向。',
      play: '30W',
      like: '1W',
      video: `${BASE_URL}media/videos/x11-official-2.mp4`,
      poster: `${BASE_URL}media/covers/c2.jpg`,
      idea: '从玩家发布的笔记中捕捉到磁吸玩法这一亮点，并判断出该玩法尚未被大众玩家广泛熟知，由此精准切入痛点发布内容。再以极具悬念感的标题与封面呈现玩法亮点，引导用户点击，最终斩获爆款。',
      douyin: 'https://v.douyin.com/ParURF3Lb7Q',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/6795f032000000001801a153?source=webshare&xhsshare=pc_web&xsec_token=ABzeoys1zjXm_MT3d_QryizhwZH3QwomE9fVh_mhWbYCY=&xsec_source=pc_share',
    },
    {
      id: 'c3',
      title: '案例视频 03 · 我将支持暖暖用美貌统治全世界！！！！！',
      playerTitle: '案例视频 03 · 我将支持暖暖用美貌统治全世界！！！！！',
      desc: '跑通主账号与矩阵账号的联动模式：主账号发掘核心内容、矩阵账号复制放大，形成可持续传播链路。',
      play: '30W',
      like: '3000+',
      video: `${BASE_URL}media/videos/x11-official-c3-nuannuan.mp4`,
      poster: `${BASE_URL}media/covers/c3.jpg`,
      idea: '洞察到玩家自发的创意玩法后，迅速跟进并复刻内容，同时联动 KOS 矩阵进行规模化扩散。以极低的制作成本，借矩阵协同之势为产品带来额外 70W+ 曝光，实现"小内容、大声量"的传播效果。',
      douyin: 'https://v.douyin.com/AKe0iV_wujQ',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/684be12300000000230156e5?source=webshare&xhsshare=pc_web&xsec_token=ABIvnmzWeg7PEzSByhVzdYpe8bvgSIQoFYRnHnS_Vu5ns=&xsec_source=pc_share',
      script: null,
    },
    {
      id: 'c4',
      title: '案例视频 04 · 为何风雪之心出生就是天角兽？又是什么公主',
      playerTitle: '案例视频 04 · 为何风雪之心出生就是天角兽？又是什么公主',
      desc: 'IP 系列内容的集大成之作，验证了对 IP 的核心洞察与起号思路。',
      play: '30W',
      like: '1W',
      video: `${BASE_URL}media/videos/x11-official-c4-fengxuezhixin.mp4`,
      poster: `${BASE_URL}media/covers/c4.jpg`,
      idea: '基于对《小马宝莉》IP 的深度了解，将内容聚焦点放在高人气的配角身上，借 IP 本身的讨论热度精准触达核心粉丝群体。看似在做角色科普，实则通过持续的内容输出建立账号的 IP 属性与人格化认知，为后续产品宣传沉淀精准粉丝基础。',
      douyin: 'https://v.douyin.com/FwYHMc_Zc1g/',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/6870ec61000000001100372c?source=webshare&xhsshare=pc_web&xsec_token=LBK4lQNhpmKczBovUcDz2MKwPJHdglY6NSt8NtrOk0bEk=&xsec_source=pc_share',
    },
    {
      id: 'c5',
      title: '案例视频 05 · 齐刘海官宣',
      playerTitle: '案例视频 05 · 齐刘海官宣',
      desc: '验证了选品能力：通过挖掘小众但具备高潜力的产品，借助官宣抢占用户心智。',
      play: '20W',
      like: '2000',
      video: '',
      poster: `${BASE_URL}media/covers/c5.jpg`,
      idea: '敏锐发掘到「别动我的齐刘海」这一高潜力 BJD 盲盒，并通过第一时间官宣的形式抢占用户心智。让原本面向全渠道通贩的"渠道品"，在用户认知中转变为"独家品"，成功引导大量用户前往线下门店购买。',
      note: '本案例为图文笔记，无视频源。',
      douyin: '',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/696df2bc000000000a02abf8?source=webshare&xhsshare=pc_web&xsec_token=ABp3THpoiDR5SFKPAb80i6YBpRoj0IN1aZl_F25qCWons=&xsec_source=pc_share',
    },
    {
      id: 'c6',
      title: '案例视频 06 · BJD 科普视频',
      playerTitle: '案例视频 06 · BJD 科普视频',
      desc: '验证了热门品类科普内容对垂类用户的吸引力，以利他性内容塑造专业号形象并精准吸引垂类粉丝。',
      play: '1W',
      like: '300+',
      video: `${BASE_URL}media/videos/x11-official-c6-bjd.mp4`,
      poster: `${BASE_URL}media/covers/c6.jpg`,
      idea: '深入了解 BJD 圈层后，精准锁定线下购买用户「不了解 BJD 尺寸」这一核心痛点。再结合门店热门产品进行深度融合创作，让科普内容既具备信息价值，也能反向带动门店到店与转化。',
      douyin: 'https://v.douyin.com/MYvKsto8OBM/',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/69b3e8b9000000001b001d4b?source=webshare&xhsshare=pc_web&xsec_token=ABGPmqbQ8kwBAdQSYFR0r4pomzBYZ60vgl2bU9ymTx4mk=&xsec_source=pc_share',
      script: null,
    },
  ],
}

export const matrixDetail = {
  id: 'x11-matrix',
  tagline: '搭建全国门店新媒体矩阵 0‑1 运营体系：将 170 + 门店分散的个体账号，通过策略、内容标准与自动化工具，打造成一套可落地、可复制、可持续放大的内容增长体系。',
  meta: '项目周期：2025.01–2026.07｜范围：全国 170+ 家门店｜角色：矩阵搭建与内容策略',
  note: '矩阵数据来自门店账号后台（2025 年 8–12 月实测）',
  dashboards: [
    {
      label: '矩阵累计笔记',
      value: '4.7万',
      desc: '门店矩阵累计产出小红书原创笔记',
      icon: 'doc',
      stat: true,
      viz: 'stacks',
    },
    {
      label: '平台爆文产出',
      value: '969篇',
      desc: '筛选出的高互动平台爆文',
      icon: 'spark',
      stat: true,
      viz: 'flames',
    },
    {
      label: '矩阵总曝光',
      value: '750W',
      desc: '门店 KOS 矩阵累计总曝光量',
      icon: 'eye',
      stat: true,
      viz: 'radar',
    },
    {
      label: '矩阵互动量',
      value: '58W+',
      desc: '门店矩阵累计互动量',
      icon: 'chat',
      stat: true,
      viz: 'social',
    },
  ],
  tags: ['门店 KOS 矩阵规模化运营', '内容标准与策略输出', 'AI 审核提效协同'],
  points: [
    {
      keys: ['0→1搭建', '170+家门店', '分阶段门店激励机制', '良性竞争氛围', '规模化复制与指数级增长'],
      text: '从0→1搭建全国170+家门店新媒体矩阵，覆盖账号创建、同城选题、内容模板到辅导发布的全链路，形成标准化可复制的运营体系。项目前期搭建分阶段门店激励机制：初期侧重发布数量快速培养门店输出习惯；后期调整激励权重转向内容质量，引导门店产出优质原创内容，调动全员积极性，营造良性竞争氛围，实现内容产出的规模化复制与指数级增长。',
    },
    {
      keys: ['迭代式可复用内容模板体系', '围绕产品完整生命周期的创作方法论', '4.7 万篇', '969 篇', '750W'],
      text: '搭建迭代式可复用内容模板体系：从基础单品模板升级为围绕产品完整生命周期的创作方法论，覆盖新品预热、上市开箱曝光、新品到店通知、成熟期玩法挖掘、刺激用户复购全场景。以标准化内容体系驱动产出：2025年下半年累计 4.7 万篇笔记、969 篇爆文，矩阵总曝光 750W。',
    },
    {
      keys: ['Vibe Coding', '钉钉MCP', 'AI智能内容审核+AI自动激励核算'],
      text: '通过 Vibe Coding 独立搭建KOS管理系统，对接钉钉MCP实现外部流程协同；落地AI智能内容审核+AI自动激励核算，以AI审核替代人工审核的繁琐流程，门店可直接查看审核、激励结果，在提升分发效率的同时大幅降低舆论风险。',
    },
  ],
  cases: [
    {
      id: 'c1',
      title: '案例视频 01 · 暹罗厘普开箱展示来咯❗❗',
      playerTitle: '案例视频 01 · 暹罗厘普开箱展示来咯❗❗',
      desc: '门店爆款视频 · 约 64 秒｜赞 1,207 · 藏 129 · 评 84 · 转 538｜广州 · 番禺永旺梦乐城',
      play: '—',
      like: '1,207',
      video: `${BASE_URL}media/videos/x11-matrix-c1-siamripllp.mp4`,
      poster: `${BASE_URL}media/covers/matrix-c1.jpg`,
      idea: '以开箱视角展示产品细节与工艺，节奏轻快、信息点清晰，撬动自然流量。',
      douyin: '',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/68d6bc16000000001101f532?source=webshare&xhsshare=pc_web&xsec_token=ABsaKDzYiAOYiDkOAwvY1DwVv8PQOGUYhfPu4Z4Ct9JvU=&xsec_source=pc_share',
      script: null,
    },
    {
      id: 'c2',
      title: '案例视频 02 · 当罗小黑从 500 平米的大床上醒来……',
      playerTitle: '案例视频 02 · 当罗小黑从 500 平米的大床上醒来……',
      desc: '门店爆款视频 · 约 8.6 秒｜赞 800 · 藏 100 · 评 50 · 转 200｜济南 · 恒隆广场',
      play: '1w',
      like: '800',
      video: `${BASE_URL}media/videos/x11-matrix-c2-xiaoheixinglai.mp4`,
      poster: `${BASE_URL}media/covers/matrix-c2.jpg`,
      idea: '以场景化脑洞设定做切入点，快速建立记忆点，带动门店账号互动。',
      douyin: '',
      xiaohongshu: '',
      script: null,
    },
    {
      id: 'c3',
      title: '案例视频 03 · 就这个轻松小熊‼️终于在成都买到了',
      playerTitle: '案例视频 03 · 就这个轻松小熊‼️终于在成都买到了',
      desc: '门店爆款笔记 · 6 张图｜赞 1,800 · 藏 200 · 评 100 · 转 1,500｜成都 · 远大购物中心',
      play: '8w',
      like: '1,800',
      video: '',
      poster: `${BASE_URL}media/covers/matrix-c3.jpg`,
      idea: '以「终于买到」的真实到店情绪做钩子，图文结合呈现购买场景。',
      douyin: '',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/68f4aab300000000040011bc?source=webshare&xhsshare=pc_web&xsec_token=ABxmBWlgTfUDRb5wjlhZOTFVgQUAwuY-exhstRI_fljew=&xsec_source=pc_share',
      note: '本案例为图文笔记，无视频源。',
      script: null,
    },
    {
      id: 'c4',
      title: '案例视频 04 · 让我们恭迎暖皇登基！！',
      playerTitle: '案例视频 04 · 让我们恭迎暖皇登基！！',
      desc: '高互动笔记｜赞 3,300 · 藏 80 · 评 30 · 转 250｜重庆 · 来福士',
      play: '12w',
      like: '3,300',
      video: `${BASE_URL}media/videos/x11-matrix-c4-nuannuanhuangji.mp4`,
      poster: `${BASE_URL}media/covers/matrix-c4.jpg`,
      idea: '围绕高热度 IP 话题做发布，借势讨论度放大门店内容声量。',
      douyin: '',
      xiaohongshu:
        'https://www.xiaohongshu.com/discovery/item/68514931000000002202669b?source=webshare&xhsshare=pc_web&xsec_token=ABFXfxWBl8IFCFRlOJQufd0Hu7PeAq5rhNvzIgKX4MhJo=&xsec_source=pc_share',
      script: null,
    },
  ],
  extra: {
    vibe: {
      heading: '2026 · Vibe Coding 自建管理系统',
      text: '尝试以 Vibe Coding 独立搭建 KOS 门店矩阵管理系统，对接钉钉MCP完成外部流程协同。\n实现两大自动化能力：①AI内容自动审核，替代传统人工审核，门店实时查看审核结果；②AI自动核算门店激励，无需人工统计。\n在简化矩阵分发全流程的同时，提升运营效率，大幅降低内容舆论风险。',
      screenshots: [],
    },
  },
}

export const matrixStages = [
  {
    id: 'pain',
    tab: '现状痛点拆解',
    title: '现状痛点拆解',
    sub: '门店账号分散，缺少统一运营规则',
    points: [
      {
        keys: ['170+ 家线下门店'],
        text: '全国 170+ 家线下门店，门店账号分散独立，无统一运营标准，产出质量参差不齐。',
      },
      {
        keys: ['内容创作思路'],
        text: '门店运营人员缺少内容创作思路，不知道拍什么、怎么发。',
      },
      {
        keys: ['激励引导机制'],
        text: '缺少有效的激励引导机制，门店发布意愿低，内容产出不稳定。',
      },
      {
        keys: ['矩阵管理成本高'],
        text: '内容审核、数据统计全部依靠人工，矩阵管理成本高，很难规模化扩张。',
      },
    ],
  },
  {
    id: 'coldstart',
    tab: '矩阵 0‑1 冷启动搭建',
    title: '矩阵 0‑1 冷启动搭建',
    sub: '设计分阶段激励机制，激活门店内容产出活力',
    points: [
      {
        keys: ['170+ 门店', '0‑1', '全链路'],
        text: '完成全国 170+ 门店矩阵从 0‑1 全链路搭建，覆盖账号开通、同城选题引导、门店运营辅导整套流程。',
      },
      {
        keys: ['分阶段门店激励方案'],
        text: '自研分阶段门店激励方案：前期激励侧重发布数量，快速培养门店发布习惯，盘活矩阵活跃度。',
      },
      {
        keys: ['激励权重'],
        text: '运营中后期动态调整激励权重，导向内容质量，引导门店主动产出高质量原创内容。',
      },
      {
        keys: ['良性竞争氛围', '规模化复制', '从“量”到“质”'],
        text: '营造良性竞争氛围，实现门店内容规模化复制，完成矩阵从“量”到“质”的过渡。',
      },
    ],
  },
  {
    id: 'content',
    tab: '内容标准与策略输出',
    title: '内容标准与策略输出',
    sub: '搭建产品全生命周期可复用内容模板体系',
    points: [
      {
        keys: ['产品全生命周期创作方法论'],
        text: '迭代门店内容模板库，由简单单品拍摄模板，升级为产品全生命周期创作方法论。',
      },
      {
        keys: ['新品预热海报', '新品上市开箱曝光', '新品到店通知', '产品成熟期玩法挖掘'],
        text: '围绕产品完整节点输出对应内容方向：新品预热海报、新品上市开箱曝光、新品到店通知、产品成熟期玩法挖掘。',
      },
      {
        keys: ['标准化内容指引'],
        text: '通过标准化内容指引，帮助门店找准创作方向，持续刺激消费者关注与复购欲望。',
      },
      {
        keys: ['创作 SOP'],
        text: '沉淀可直接复用的创作 SOP，降低门店的创作门槛，保障矩阵内容稳定输出。',
      },
    ],
  },
  {
    id: 'vibe',
    tab: 'Vibe Coding 自建系统提效',
    title: 'Vibe Coding 自建管理系统提效',
    sub: '对接钉钉 MCP，实现矩阵运营自动化',
    points: [
      {
        keys: ['Vibe Coding', '钉钉 MCP'],
        text: '使用 Vibe Coding 独立搭建 KOS 门店矩阵管理系统，对接钉钉 MCP 完成外部流程协同。',
      },
      {
        keys: ['AI 智能内容审核'],
        text: '落地 AI 智能内容审核：替代传统人工审核流程，门店可实时查看审核结果，降低舆论风险。',
      },
      {
        keys: ['AI 自动核算'],
        text: 'AI 自动核算门店激励，告别人工统计核算，减少大量重复人力工作。',
      },
      {
        keys: ['全链路自动化'],
        text: '实现矩阵分发、审核、激励全链路自动化，大幅提升矩阵整体运营效率。',
      },
    ],
  },
]

export const strengths = [
  {
    no: '01',
    icon: 'PenLine',
    title: '短视频脚本 & 爆款文案',
    desc: '海内外脚本创作，打造千万级爆款',
  },
  {
    no: '02',
    icon: 'Clapperboard',
    title: '内容策划与拍摄编导',
    desc: '选题、拍摄统筹，把控内容全链路质量',
  },
  {
    no: '03',
    icon: 'LayoutGrid',
    title: '矩阵规模化运营',
    desc: '0→1 搭建账号 / 门店矩阵，输出标准化运营方案',
  },
  {
    no: '04',
    icon: 'Video',
    title: '拍摄统筹 & 后期把控',
    desc: '对接团队，把控成片效果',
  },
  {
    no: '05',
    icon: 'Globe2',
    title: '海内外多平台运营',
    desc: '抖音 / 小红书 / B 站 / TikTok / Instagram / YouTube 多平台流量理解，数据复盘迭代',
  },
  {
    no: '06',
    icon: 'Bot',
    title: 'AI 工具应用',
    desc: 'AI 搭建效率工作台，赋能内容生产',
  },
]
